name: "Lukasz Dechnik"
description: "My personal website"
domain: "dev.dechnik.net"

dark_scheme: gruvbox-dark-medium
light_scheme: gruvbox-dark-medium
printing_scheme: tomorrow # Must have #FFFFFF background


plugins:
  - jekyll-extlinks
  - jekyll-relative-links

extlinks:
  attributes: 
    class: external

relative_links:
  enabled: true
  collections: true

sass:
  style: compact

kramdown:
  syntx_highlighter: coderay


include: [".well-known"]

source: _src

collections:
  posts:
    output: true
    permalink: /blog/:path/index:output_ext
    name: Posts

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post.html"
      nav_current: "/blog/"
  -
    scope:
      path: ""
    values:
      layout: "default.html"
      language: "en"
      author: "Lukasz Dechnik"
